### PR TITLE
Add a function to create headers from byte arrays without any transmute

### PR DESCRIPTION
**Pull request by est31**

### CODE REVIEW

**Comment by est31** [comment]
After merging of this PR, I'd love to have a (minor) release.

**Comment by est31** [comment]
It's not really important though as I can use a transmute for now.

**Comment by alexcrichton** [comment]
This is a pretty large argument to be passing around, perhaps this could be switched to take a slice? We could also have it take a variable-length slice, assert it's 512 bytes, and then return a reference.

**Comment by est31** [comment]
@alexcrichton is it better now? I'll need to test this version of the function first whether it actually works...

**Comment by alexcrichton** [comment]
Yeah that looks fine by me, although could this take `&[u8]` instead of `&[u8; 512]`? I imagine the latter is very difficult to construct...

**Comment by est31** [comment]
> I imagine the latter is very difficult to construct...

[Indeed](https://github.com/rust-lang/rfcs/issues/1772)... My code can manage as it serializes from/to the array directly, but I'll change it to `&[u8]`. As slices also need to store the length, I'll have to convert the slice to a pointer.

**Comment by est31** [comment]
Please don't merge this yet, I haven't verified whether it does what I want it to. With unsafe code you never know...

**Comment by est31** [comment]
Hmm right there seems to be an issue here where we invoke UB... Let me see whether I can fix this.

**Comment by est31** [comment]
Yup, it is fixed now. r? @alexcrichton

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
