### PR TITLE
Archiving hard link

### PR DESCRIPTION
**Pull request by BrianOn99**
Fix issue #119 
I have not tested the code in redox and windows.

There is a little bit code duplication in `append_fs` but I cannot find a good solution.  Any advice would be welcome.

### CODE REVIEW

**Comment by BrianOn99** [comment]
I have fixed the warings in windows build.

**Comment by alexcrichton** [comment]
Thanks for the PR! It looks like there's a fair bit of code movement here, could the code stay where it was primarily, outside the generic functions? Additionally could some restructuring perhaps help the amount of `#[cfg]` traffic?

**Comment by BrianOn99** [comment]
There is quite a lot of code movement because a HashMap has to be accessed to find a hard link.  I moved those functions to methods so that the HashMap need not be passed around.  That makes the argument list shorter.  If that is not reasonable I can move them back.

As for the `#[cfg]`, the difficulty is I cannot find an open source implementation of tar on windows supporting hardlink.  I am not experienced on windows either.  Any suggestion will be appreciated!

**Comment by alexcrichton** [comment]
Hm ok I definitely want to keep the implementations here outside of the generic functions, that may require some refactoring though to avoid passing too many parameters everywhere.

For Windows I do believe there's the basic equivalent of inodes. The [`same-file` crate](https://docs.rs/same-file/1.0.0/same_file/) may be useful here as well

**Comment by BrianOn99** [comment]
@alexcrichton Thanks for the response.  I will move the implementations away, perhaps later this week.

As for windows, to my understanding using `same-file` may not be a good approach.  In unix we only record and find hard link when hard link count > 1, which save lots of memory and time.  And accessing HashMap is quite fast.  But to use `same-file` we have to record every file, and call `is_same_file` for every (recorded file, currentfile) pair, so it is O(n^2) for n = number of files.  Again I have no experience in windows API so I cannot think out a better approach.  Any expert here?

**Comment by BrianOn99** [comment]
The requirements are:
1. `append_fs`, `append_path`, etc, have to be implemented outside `impl Buider`.
2. reduce number of `cfg`.
3. (my own requirement) not perform poorly when there are many files.

And in current situation I cannot find a way to meet all of them simultaneously.  To achieve [2] we can consider using `same-file` crate, but then [3] cannot be achieved, as mentioned above.  In the current state, trying to achieve [1] will violate [2] because I need to make version in of `append_fs` which takes a HashMap, and windows version does not take `HashMap`.

So I am closing this PR.  If anyone is interested feel free to use my commits.

**Pull request closed without merging**
