### PR TITLE
handle extended numeric formats in octal_from

### LINKED ISSUE #130: failure "numeric field did not have utf-8 text" with large files in archive
```
cargo new example
cd example
fallocate -l 8G large.file
tar cf large.tar large.file
echo 'tar = "0.4"' >> Cargo.toml
cat << EOF > src/lib.rs
extern crate tar;

use std::fs::File;
use tar::Archive;

#[test]
fn load() {
    let archive = File::open("large.tar").unwrap();
    let mut archive = Archive::new(archive);
    for entry in archive.entries().unwrap() {
        entry.unwrap();
    }
}
EOF
cargo test
```

results in

```
running 1 test
test load ... FAILED

failures:

---- load stdout ----
        thread 'load' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("numeric field did not have utf-8 text") }) }', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    load

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

edit: fails with 8GB file at a minimum, I had 36GB  before

### PR DESCRIPTION
**Pull request by cake4289**
fixes #130

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Do you know of some docs online where this could link to which explain this extension?

**Comment by cake4289** [comment]
See https://www.freebsd.org/cgi/man.cgi?query=tar&sektion=5&manpath=FreeBSD+8-current under section "Numeric Extensions".

**Comment by cake4289** [comment]
might want to do this in octal_into as well I guess though I haven't done that here

**Comment by alexcrichton** [comment]
Ok thanks! Could you add that link in the code?

Also, perhaps we could avoid changing `octal_into`? It sounds like this isn't a super-well-supported encoding and AFAIK there weren't many problems with the previous incarnation?

**Comment by cake4289** [comment]
done & done

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
